# Render Deployment Configuration for Vicky-Chats

services:
  - type: web
    name: vicky-chats-web
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node index.js"
    envVars:
      - key: MONGODB_URI
        sync: false
    autoDeploy: true
